    - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'  # or any version like '1.22', 'stable'

      - name: Install dependencies
        run: go mod tidy
